### PR TITLE
feat: Upgrade terraform-provider-equinix to v2.8.0

### PR DESCRIPTION
**Pull request by euclid-eqx**
This PR was generated via `$ upgrade-provider equinix/pulumi-equinix --kind=provider --target-bridge-version=latest --pr-title-prefix=feat:  --java-version=0.16.1`.

---

- Updating Java Gen version to 0.16.1.
- Upgrading terraform-provider-equinix from 2.5.0  to 2.8.0.

### CODE REVIEW

**Comment by thogarty** [comment]
I don't think this one should be merged. It's missing important details regarding new resources. I'm actively working on creating a separate PR that will upgrade Pulumi to latest Equinix Terraform

**Comment by ctreatma** [comment]
> regarding new resources

The automated PRs intentionally do not add mappings for new resources.  This is so that hand-written PRs that _do_ add new resources can be focused on just that; otherwise those PRs are far too large to be reviewed accurately.

**Comment by thogarty** [comment]
> > regarding new resources
> 
> The automated PRs intentionally do not add mappings for new resources. This is so that hand-written PRs that _do_ add new resources can be focused on just that; otherwise those PRs are far too large to be reviewed accurately.

Alright copy that. What's the right timing then? You upgrade the Pulumi to latest Terraform then add the mappings in a PR after? I was getting some errors locally saying that the mappings are needed in order to upgrade to a Terraform Version that had them.

**Comment by thogarty** [comment]
Closing. Out of date because of #225

**Pull request closed without merging**
