### PR TITLE
chore(ci): skip mapping errors when upgrading the Terraform provider

### PR DESCRIPTION
**Pull request by ctreatma**
Pretty much every time we upgrade the upstream Terraform provider, the upgrade fails due to one of the following:

- Addition or removal of a resource/data source
- Changes to examples

As a result we are, in practice, doing a manual upgrade of the Pulumi provider for almost every release of the Terraform provider.  Those manual upgrade PRs also end up being overly large and difficult to review because they _also_ include changes to add or remove features in parity with the upstream provider, _and_ possibly-accidental upgrades of surrounding tooling.

This updates the upgrade-provider GitHub Actions workflow to define environment variables that make [the provider upgrade process more resilient to upstream changes](https://github.com/pulumi/pulumi-terraform-bridge/tree/cb8c4edbc8e3cc9772716db635b26de0b217a9f7?tab=readme-ov-file#design-time-options).  The script to generate examples is also updated so that issues with example conversion result in missing examples rather than a failed upgrade.

The intent of these changes is to enable automation to do its job as well as possible, and allow follow-up contributions to focus narrowly on fixing examples or adding/removing resources.

### CODE REVIEW

**Comment by ctreatma** [comment]
For some reason the changes to the example script are not having the same effect in CI that they do locally.  [Manually running the upgrade job on this branch fails](https://github.com/equinix/pulumi-equinix/actions/runs/11166030234), but when I run what I _think_ are the equivalent commands locally, it succeeds.

**Comment by ocobles** [comment]
> For some reason the changes to the example script are not having the same effect in CI that they do locally. [Manually running the upgrade job on this branch fails](https://github.com/equinix/pulumi-equinix/actions/runs/11166030234), ~but when I run what I _think_ are the equivalent commands locally, it succeeds.~ I had been running the `./upstream.sh ...` commands to update the submodule, followed by `make tfgen`, and _that_ succeeded. When I instead installed and ran `upgrade-provider`, it failed but in a slightly different place than it does in CI.
> 
> I see some kind of repo checkout happening during `upgrade-provider` execution; does that command use scripts and/or Makefile from the `main` branch rather than using the local files?

Yes it checkouts to main branch 

```
pull default branch
✓ /usr/local/bin/git ls-remote --heads origin: done
✓ finding default branch: master
✓ /usr/local/bin/git checkout master: done
✓ /usr/local/bin/git pull origin: done
```

**Review by ocobles — APPROVED** [review]
nice! while checking PULUMI_SKIP_MISSING_MAPPING_ERROR / PULUMI_SKIP_EXTRA_MAPPING_ERROR documentation I learned about this option https://github.com/pulumi/pulumi-terraform-bridge/blob/master/docs/autofill.md which can be useful for us too

**Comment by ocobles** [comment]
It's also worth mentioning that it seems now there is more control over how examples are generated by default, perhaps by making some changes to Terraform, the script to generate examples is not needed at all.

**Pull request merged**
